POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "name": "", 
   "email": "" ,
   "password": "",
   "role": ""
}

### 

POST http://localhost:3003/user/login
Content-Type: application/json

{
  "email": "keldev9@gmail.com" ,
   "password": "123456"
}

### 

GET http://localhost:3003/user/profile
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxZTRkZThlLWMxOTQtNDIyYi1iMzUyLWE1Mzg4YmY3N2UwNCIsImlhdCI6MTYyMzQyNTM4NiwiZXhwIjoxNjIzNDY4NTg2fQ.q4a1BDHwwEbnTNGN0EclR9VF4zseTpOOn5LK4UBgb7Y
### 

GET http://localhost:3003/user/feed
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxZTRkZThlLWMxOTQtNDIyYi1iMzUyLWE1Mzg4YmY3N2UwNCIsImlhdCI6MTYyMzQyNTM4NiwiZXhwIjoxNjIzNDY4NTg2fQ.q4a1BDHwwEbnTNGN0EclR9VF4zseTpOOn5LK4UBgb7Y

###

POST http://localhost:3003/create/recipe
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxZTRkZThlLWMxOTQtNDIyYi1iMzUyLWE1Mzg4YmY3N2UwNCIsImlhdCI6MTYyMzQyNTM4NiwiZXhwIjoxNjIzNDY4NTg2fQ.q4a1BDHwwEbnTNGN0EclR9VF4zseTpOOn5LK4UBgb7Y

{
   "title": "coxinha", 
   "description": "Modo de Preparo Leve ao fogo o leite, a margarina e o caldo. Deixe ferver. Despeje de uma só vez o trigo e mexa bem. Depois retire da panela e coloque sobre a mesa. Sove um pouco e comece a modelar." 
}

###
GET http://localhost:3003/recipe/99d514dc-ccac-4df5-8656-33f37f1c749b
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxZTRkZThlLWMxOTQtNDIyYi1iMzUyLWE1Mzg4YmY3N2UwNCIsImlhdCI6MTYyMzQxOTc4OSwiZXhwIjoxNjIzNDYyOTg5fQ.oF0w-52AAJw5Vc5r5Qeil9qmR6yd8pPQ-p_QjwAW8Eg

###

GET http://localhost:3003/users/8aaa4695-c019-4a21-baec-1b7c5d804cd1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxZTRkZThlLWMxOTQtNDIyYi1iMzUyLWE1Mzg4YmY3N2UwNCIsImlhdCI6MTYyMzQyNTM4NiwiZXhwIjoxNjIzNDY4NTg2fQ.q4a1BDHwwEbnTNGN0EclR9VF4zseTpOOn5LK4UBgb7Y


### 

POST http://localhost:3003/user/follow
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxZTRkZThlLWMxOTQtNDIyYi1iMzUyLWE1Mzg4YmY3N2UwNCIsImlhdCI6MTYyMzQxOTc4OSwiZXhwIjoxNjIzNDYyOTg5fQ.oF0w-52AAJw5Vc5r5Qeil9qmR6yd8pPQ-p_QjwAW8Eg

{
   "userToFollowId": "8aaa4695-c019-4a21-baec-1b7c5d804cd1"
}

###
POST http://localhost:3003/user/unfollow
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxZTRkZThlLWMxOTQtNDIyYi1iMzUyLWE1Mzg4YmY3N2UwNCIsImlhdCI6MTYyMzQxOTc4OSwiZXhwIjoxNjIzNDYyOTg5fQ.oF0w-52AAJw5Vc5r5Qeil9qmR6yd8pPQ-p_QjwAW8Eg

{
   "userToUnfollowId": "8aaa4695-c019-4a21-baec-1b7c5d804cd1"
}

### 

PUT http://localhost:3003/edit/recipe
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhhYWE0Njk1LWMwMTktNGEyMS1iYWVjLTFiN2M1ZDgwNGNkMSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MjM0MzY5OTUsImV4cCI6MTYyMzQ4MDE5NX0.pJjq5UPBsUAKEOcQi1_Ctep9Rj9M4EloUzD61NA_uJQ

{
   "title": "Bolo simples", 
   "description": "Esse bolo simples é uma daquelas receitas básicas e deliciosas: ele pode ser incrementado com calda de chocolate, recheio de brigadeiro, doce de leite e outras delícias.", 
   "recipeId": "99d514dc-ccac-4df5-8656-33f37f1c749b"
}

### 

DELETE http://localhost:3003/delete/recipe/99d514dc-ccac-4df5-8656-33f37f1c749b
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhhYWE0Njk1LWMwMTktNGEyMS1iYWVjLTFiN2M1ZDgwNGNkMSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2MjM0MzY5OTUsImV4cCI6MTYyMzQ4MDE5NX0.pJjq5UPBsUAKEOcQi1_Ctep9Rj9M4EloUzD61NA_uJQ