POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "name": "Eduardo", 
   "email": "eduardo@gmail.com" ,
   "password": "ilikebatman"
}

### 

POST http://localhost:3003/user/login
Content-Type: application/json

{
  "email": "eduardo@gmail.com" ,
   "password": "ilikebatman"
}

### 

GET http://localhost:3003/user/profile
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhhYWE0Njk1LWMwMTktNGEyMS1iYWVjLTFiN2M1ZDgwNGNkMSIsImlhdCI6MTYyMzM0ODM4MSwiZXhwIjoxNjIzMzkxNTgxfQ.5At0AkRN0jcYXrVqvdOQHjhO7hnv7FqY3i_XqZYy_d4

###

POST http://localhost:3003/create/recipe
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhhYWE0Njk1LWMwMTktNGEyMS1iYWVjLTFiN2M1ZDgwNGNkMSIsImlhdCI6MTYyMzM0ODM4MSwiZXhwIjoxNjIzMzkxNTgxfQ.5At0AkRN0jcYXrVqvdOQHjhO7hnv7FqY3i_XqZYy_d4

{
   "title": "brigadeiro", 
   "description": "Com o brigadeiro frio, passe manteiga, água ou óleo de coco nas mão e com uma colher pequena pegue porções do doce e enrole rapidamente, e então passe pelo granulado." 
}

###

GET http://localhost:3003/users/8aaa4695-c019-4a21-baec-1b7c5d804cd1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxZTRkZThlLWMxOTQtNDIyYi1iMzUyLWE1Mzg4YmY3N2UwNCIsImlhdCI6MTYyMzM1ODA4NywiZXhwIjoxNjIzNDAxMjg3fQ.1_L3ErNlCSFO50gxKuUHNtWQS81Mf7TNkDzga39SQcQ


### 

POST http://localhost:3003/user/follow
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQxZTRkZThlLWMxOTQtNDIyYi1iMzUyLWE1Mzg4YmY3N2UwNCIsImlhdCI6MTYyMzQxOTc4OSwiZXhwIjoxNjIzNDYyOTg5fQ.oF0w-52AAJw5Vc5r5Qeil9qmR6yd8pPQ-p_QjwAW8Eg

{
   "userToFollowId": "8aaa4695-c019-4a21-baec-1b7c5d804cd1"
}